---
Name: fulltextsearchconfig
---
SilverStripe\ORM\DataObject:
  extensions:
    - SilverStripe\FullTextSearch\Search\Extensions\SearchUpdater_ObjectHandler
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - SilverStripe\FullTextSearch\Solr\Control\ContentControllerExtension
