---
Name: fulltextsearchmysql
After:
  - 'databaseconnectors'
---
SilverStripe\Core\Injector\Injector:
  MySQLDatabase:
    class: SilverStripe\FullTextSearch\Search\Captures\SearchManipulateCapture_MySQLDatabase
  MySQLPDODatabase:
    class: SilverStripe\FullTextSearch\Search\Captures\SearchManipulateCapture_MySQLDatabase

---
Name: fulltextsearchpostgresql
After:
  - 'postgresqlconnectors'
---
SilverStripe\Core\Injector\Injector:
  PostgrePDODatabase:
    class: SilverStripe\FullTextSearch\Search\Captures\SearchManipulateCapture_PostgreSQLDatabase
  PostgreSQLDatabase:
    class: SilverStripe\FullTextSearch\Search\Captures\SearchManipulateCapture_PostgreSQLDatabase

---
Name: fulltextsearchsqlite
---
SilverStripe\Core\Injector\Injector:
  SQLite3Database:
    class: SilverStripe\FullTextSearch\Search\Captures\SearchManipulateCapture_SQLite3Database
